-- =============================================================================
-- IS_LAST 트리거용 인덱스 추가
-- 바코드 + IS_LAST 복합 인덱스 (트리거에서 UPDATE 대상 조회 최적화)
-- =============================================================================

CREATE INDEX IDX_LOG_AOI_ISLAST ON LOG_AOI(SERIAL_NO, IS_LAST);
CREATE INDEX IDX_LOG_COATING1_ISLAST ON LOG_COATING1(BARCODE, IS_LAST);
CREATE INDEX IDX_LOG_COATING2_ISLAST ON LOG_COATING2(BARCODE, IS_LAST);
CREATE INDEX IDX_LOG_COATINGREVIEW_ISLAST ON LOG_COATINGREVIEW(MAIN_BARCODE, IS_LAST);
CREATE INDEX IDX_LOG_COATINGVISION_ISLAST ON LOG_COATINGVISION(MAIN_BARCODE, IS_LAST);
CREATE INDEX IDX_LOG_DOWNLOAD_ISLAST ON LOG_DOWNLOAD(BARCODE, IS_LAST);
CREATE INDEX IDX_LOG_EOL_ISLAST ON LOG_EOL(BARCODE, IS_LAST);
CREATE INDEX IDX_LOG_FCT_ISLAST ON LOG_FCT(BARCODE, IS_LAST);
CREATE INDEX IDX_LOG_ICT_ISLAST ON LOG_ICT(BARCODE, IS_LAST);
CREATE INDEX IDX_LOG_LOWCURRENT_ISLAST ON LOG_LOWCURRENT(BARCODE, IS_LAST);
CREATE INDEX IDX_LOG_MAOI_ISLAST ON LOG_MAOI(SERIAL_NO, IS_LAST);
CREATE INDEX IDX_LOG_MARKING_ISLAST ON LOG_MARKING(MAIN_BARCODE, IS_LAST);
CREATE INDEX IDX_LOG_SPI_ISLAST ON LOG_SPI(MASTER_BARCODE, IS_LAST);
CREATE INDEX IDX_LOG_VISION_LEGACY_ISLAST ON LOG_VISION_LEGACY(BARCODE, IS_LAST);
CREATE INDEX IDX_LOG_VISION_NATIVE_ISLAST ON LOG_VISION_NATIVE(BARCODE, IS_LAST);
