-- LOG_SPI 테이블 불필요 컬럼 제거
-- CSV 첫번째 섹션(PCB 정보)만 사용하므로 나머지 컬럼 DROP
-- 실행일: 2026-03-29

ALTER TABLE LOG_SPI DROP (INSPECTION_END_TIME, TOTAL_PANEL_COUNT, JOB_NAME, USER_ID, LOT_INFO, MACHINE_ID, SIDE);
