-- =============================================================================
--  LOG_PRESSFIT — PRESSFIT 압입기 raw 로그 테이블
-- =============================================================================
--  원본: 하루치 누적 CSV (파일명 예: 20260713.csv), 헤더 1줄 + 데이터 N행
--        134칸 = 고정 9 + 높이 124포인트 + 후행 빈칸(버림)
--
--  높이 124포인트는 와이드로 둔다 (H001~H124). 포인트 수가 고정이라
--  별도 디테일 테이블로 정규화하지 않는다.
--
--  중복 처리: backend BARCODE_REPLACE_TABLES 가 BARCODE 단위 DELETE 후
--  bulk INSERT 한다. 누적 파일이 통째로 재전송돼도 중복이 쌓이지 않는다.
--
--  ACTUAL_DATE/SHIFT_CODE/ZONE_CODE 는 TRG_LOG_PRESSFIT_IS_LAST 가 채운다.
-- =============================================================================

CREATE TABLE LOG_PRESSFIT (
  LOG_ID               NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  EQUIPMENT_ID         VARCHAR2(50)     NOT NULL,
  LINE_CODE            VARCHAR2(50),
  LOG_TIMESTAMP        TIMESTAMP DEFAULT SYSTIMESTAMP,
  FILE_NAME            VARCHAR2(500),
  SEQ_NO               VARCHAR2(20)    ,
  BARCODE              VARCHAR2(100)   ,
  CONNECTOR_BARCODE    VARCHAR2(200)   ,
  STAGE_NO             VARCHAR2(10)    ,
  TOTAL_RESULT         VARCHAR2(20)    ,
  CYCLE_TIME           VARCHAR2(20)    ,
  PRESS_RESULT         VARCHAR2(20)    ,
  PRESS_VALUE          VARCHAR2(30)    ,
  HEIGHT_RESULT        VARCHAR2(20)    ,
  H001                 VARCHAR2(20)    ,
  H002                 VARCHAR2(20)    ,
  H003                 VARCHAR2(20)    ,
  H004                 VARCHAR2(20)    ,
  H005                 VARCHAR2(20)    ,
  H006                 VARCHAR2(20)    ,
  H007                 VARCHAR2(20)    ,
  H008                 VARCHAR2(20)    ,
  H009                 VARCHAR2(20)    ,
  H010                 VARCHAR2(20)    ,
  H011                 VARCHAR2(20)    ,
  H012                 VARCHAR2(20)    ,
  H013                 VARCHAR2(20)    ,
  H014                 VARCHAR2(20)    ,
  H015                 VARCHAR2(20)    ,
  H016                 VARCHAR2(20)    ,
  H017                 VARCHAR2(20)    ,
  H018                 VARCHAR2(20)    ,
  H019                 VARCHAR2(20)    ,
  H020                 VARCHAR2(20)    ,
  H021                 VARCHAR2(20)    ,
  H022                 VARCHAR2(20)    ,
  H023                 VARCHAR2(20)    ,
  H024                 VARCHAR2(20)    ,
  H025                 VARCHAR2(20)    ,
  H026                 VARCHAR2(20)    ,
  H027                 VARCHAR2(20)    ,
  H028                 VARCHAR2(20)    ,
  H029                 VARCHAR2(20)    ,
  H030                 VARCHAR2(20)    ,
  H031                 VARCHAR2(20)    ,
  H032                 VARCHAR2(20)    ,
  H033                 VARCHAR2(20)    ,
  H034                 VARCHAR2(20)    ,
  H035                 VARCHAR2(20)    ,
  H036                 VARCHAR2(20)    ,
  H037                 VARCHAR2(20)    ,
  H038                 VARCHAR2(20)    ,
  H039                 VARCHAR2(20)    ,
  H040                 VARCHAR2(20)    ,
  H041                 VARCHAR2(20)    ,
  H042                 VARCHAR2(20)    ,
  H043                 VARCHAR2(20)    ,
  H044                 VARCHAR2(20)    ,
  H045                 VARCHAR2(20)    ,
  H046                 VARCHAR2(20)    ,
  H047                 VARCHAR2(20)    ,
  H048                 VARCHAR2(20)    ,
  H049                 VARCHAR2(20)    ,
  H050                 VARCHAR2(20)    ,
  H051                 VARCHAR2(20)    ,
  H052                 VARCHAR2(20)    ,
  H053                 VARCHAR2(20)    ,
  H054                 VARCHAR2(20)    ,
  H055                 VARCHAR2(20)    ,
  H056                 VARCHAR2(20)    ,
  H057                 VARCHAR2(20)    ,
  H058                 VARCHAR2(20)    ,
  H059                 VARCHAR2(20)    ,
  H060                 VARCHAR2(20)    ,
  H061                 VARCHAR2(20)    ,
  H062                 VARCHAR2(20)    ,
  H063                 VARCHAR2(20)    ,
  H064                 VARCHAR2(20)    ,
  H065                 VARCHAR2(20)    ,
  H066                 VARCHAR2(20)    ,
  H067                 VARCHAR2(20)    ,
  H068                 VARCHAR2(20)    ,
  H069                 VARCHAR2(20)    ,
  H070                 VARCHAR2(20)    ,
  H071                 VARCHAR2(20)    ,
  H072                 VARCHAR2(20)    ,
  H073                 VARCHAR2(20)    ,
  H074                 VARCHAR2(20)    ,
  H075                 VARCHAR2(20)    ,
  H076                 VARCHAR2(20)    ,
  H077                 VARCHAR2(20)    ,
  H078                 VARCHAR2(20)    ,
  H079                 VARCHAR2(20)    ,
  H080                 VARCHAR2(20)    ,
  H081                 VARCHAR2(20)    ,
  H082                 VARCHAR2(20)    ,
  H083                 VARCHAR2(20)    ,
  H084                 VARCHAR2(20)    ,
  H085                 VARCHAR2(20)    ,
  H086                 VARCHAR2(20)    ,
  H087                 VARCHAR2(20)    ,
  H088                 VARCHAR2(20)    ,
  H089                 VARCHAR2(20)    ,
  H090                 VARCHAR2(20)    ,
  H091                 VARCHAR2(20)    ,
  H092                 VARCHAR2(20)    ,
  H093                 VARCHAR2(20)    ,
  H094                 VARCHAR2(20)    ,
  H095                 VARCHAR2(20)    ,
  H096                 VARCHAR2(20)    ,
  H097                 VARCHAR2(20)    ,
  H098                 VARCHAR2(20)    ,
  H099                 VARCHAR2(20)    ,
  H100                 VARCHAR2(20)    ,
  H101                 VARCHAR2(20)    ,
  H102                 VARCHAR2(20)    ,
  H103                 VARCHAR2(20)    ,
  H104                 VARCHAR2(20)    ,
  H105                 VARCHAR2(20)    ,
  H106                 VARCHAR2(20)    ,
  H107                 VARCHAR2(20)    ,
  H108                 VARCHAR2(20)    ,
  H109                 VARCHAR2(20)    ,
  H110                 VARCHAR2(20)    ,
  H111                 VARCHAR2(20)    ,
  H112                 VARCHAR2(20)    ,
  H113                 VARCHAR2(20)    ,
  H114                 VARCHAR2(20)    ,
  H115                 VARCHAR2(20)    ,
  H116                 VARCHAR2(20)    ,
  H117                 VARCHAR2(20)    ,
  H118                 VARCHAR2(20)    ,
  H119                 VARCHAR2(20)    ,
  H120                 VARCHAR2(20)    ,
  H121                 VARCHAR2(20)    ,
  H122                 VARCHAR2(20)    ,
  H123                 VARCHAR2(20)    ,
  H124                 VARCHAR2(20)    ,
  ACTUAL_DATE          DATE,
  SHIFT_CODE           VARCHAR2(2),
  ZONE_CODE            VARCHAR2(2),
  IS_LAST              VARCHAR2(1) DEFAULT 'N',
  IS_SAMPLE            VARCHAR2(1) DEFAULT 'N',
  CREATED_AT           TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_LOG_PRESSFIT PRIMARY KEY (LOG_ID)
)
/

CREATE INDEX IX_LOG_PRESSFIT_BARCODE ON LOG_PRESSFIT (BARCODE)
/

CREATE INDEX IX_LOG_PRESSFIT_ACTUAL ON LOG_PRESSFIT (ACTUAL_DATE, EQUIPMENT_ID)
/

COMMENT ON COLUMN LOG_PRESSFIT.SEQ_NO IS '순번 (CSV No.)'
/
COMMENT ON COLUMN LOG_PRESSFIT.BARCODE IS 'PCB 바코드'
/
COMMENT ON COLUMN LOG_PRESSFIT.CONNECTOR_BARCODE IS '커넥터 바코드'
/
COMMENT ON COLUMN LOG_PRESSFIT.STAGE_NO IS '스테이지 번호 (1/2)'
/
COMMENT ON COLUMN LOG_PRESSFIT.TOTAL_RESULT IS '전체 판정 (OK/NG)'
/
COMMENT ON COLUMN LOG_PRESSFIT.CYCLE_TIME IS '사이클 타임(초)'
/
COMMENT ON COLUMN LOG_PRESSFIT.PRESS_RESULT IS '압입 판정 (OK/NG)'
/
COMMENT ON COLUMN LOG_PRESSFIT.PRESS_VALUE IS '압입력 (예: 1.91447kN)'
/
COMMENT ON COLUMN LOG_PRESSFIT.HEIGHT_RESULT IS '높이 판정 (OK/NG)'
/
COMMENT ON COLUMN LOG_PRESSFIT.H001 IS '높이 측정 포인트 001 (H001~H124, mm)'
/
COMMENT ON COLUMN LOG_PRESSFIT.ACTUAL_DATE IS '작업일자 (트리거 자동 설정)'
/
COMMENT ON COLUMN LOG_PRESSFIT.SHIFT_CODE IS '근무조 (트리거 자동 설정)'
/
COMMENT ON COLUMN LOG_PRESSFIT.ZONE_CODE IS '타임존 (트리거 자동 설정)'
/
COMMENT ON TABLE LOG_PRESSFIT IS 'PRESSFIT 압입기 원본 로그 (1행 = PCB 1장 압입)'
/
