-- =============================================================================
--  ISCM_ICT 로그 3테이블 → 단일 테이블 통합 마이그레이션
-- =============================================================================
--  실행 사이트: SVEHICLEPDB
--  1) 기존 3테이블 DROP (LOG_ISCM_ICT / _HDATA / _COMP, 연결 트리거 포함)
--  2) 단일 LOG_ISCM_ICT 재생성 (헤더 5종 + Component 12필드)
--  3) 작업일자 컬럼(ACTUAL_DATE/SHIFT_CODE/ZONE_CODE) 추가 — LOG_ICT 정의 복사
--  4) 트리거는 trg_is_last_iscm_ict.sql 로 별도 적용
--  멱등: DROP 은 없는 객체 무시. 재실행 안전(단, 데이터는 초기화됨).
-- =============================================================================

-- ── 1) 기존 3테이블 DROP ──
BEGIN
  FOR t IN (SELECT column_value AS tab FROM TABLE(sys.odcivarchar2list(
              'LOG_ISCM_ICT', 'LOG_ISCM_ICT_HDATA', 'LOG_ISCM_ICT_COMP'))) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.tab || ' CASCADE CONSTRAINTS PURGE';
      DBMS_OUTPUT.PUT_LINE('DROPPED: ' || t.tab);
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;  -- ORA-00942: 테이블 없음 → 무시
        DBMS_OUTPUT.PUT_LINE('SKIP (no table): ' || t.tab);
    END;
  END LOOP;
END;
/

-- ── 2) 단일 LOG_ISCM_ICT 재생성 ──
CREATE TABLE LOG_ISCM_ICT (
  LOG_ID           NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  EQUIPMENT_ID     VARCHAR2(50) NOT NULL,
  LINE_CODE        VARCHAR2(50),
  LOG_TIMESTAMP    TIMESTAMP DEFAULT SYSTIMESTAMP,
  FILE_NAME        VARCHAR2(500),
  BARCODE          VARCHAR2(100),
  TOTAL_RESULT     VARCHAR2(50),
  RESULT_CURRENT   VARCHAR2(100),
  HEX_FILE_1       VARCHAR2(500),
  HEX_FILE_2       VARCHAR2(500),
  HEX_FILE_3       VARCHAR2(500),
  HEX_FILE_4       VARCHAR2(500),
  HEX_FILE_5       VARCHAR2(500),
  HEX_FILE_6       VARCHAR2(500),
  HEX_FILE_7       VARCHAR2(500),
  HEX_FILE_8       VARCHAR2(500),
  HEX_FILE_9       VARCHAR2(500),
  HEX_FILE_10      VARCHAR2(500),
  HEX_FILE_11      VARCHAR2(500),
  HEX_FILE_12      VARCHAR2(500),
  HEX_FILE_13      VARCHAR2(500),
  HEX_FILE_14      VARCHAR2(500),
  HEX_FILE_15      VARCHAR2(500),
  HEX_FILE_16      VARCHAR2(500),
  CRC_1            VARCHAR2(100),
  CRC_2            VARCHAR2(100),
  CRC_3            VARCHAR2(100),
  CRC_4            VARCHAR2(100),
  CRC_5            VARCHAR2(100),
  CRC_6            VARCHAR2(100),
  CRC_7            VARCHAR2(100),
  CRC_8            VARCHAR2(100),
  CRC_9            VARCHAR2(100),
  CRC_10           VARCHAR2(100),
  CRC_11           VARCHAR2(100),
  CRC_12           VARCHAR2(100),
  CRC_13           VARCHAR2(100),
  CRC_14           VARCHAR2(100),
  CRC_15           VARCHAR2(100),
  CRC_16           VARCHAR2(100),
  SEQ_NO           VARCHAR2(20),
  PART_NAME        VARCHAR2(500),
  ACT_V            VARCHAR2(500),
  STD_V            VARCHAR2(500),
  MSR_V            VARCHAR2(500),
  HLIM             VARCHAR2(500),
  LLIM             VARCHAR2(500),
  HPIN             VARCHAR2(500),
  LPIN             VARCHAR2(500),
  PART_TYPE        VARCHAR2(500),
  RESULT           VARCHAR2(50),
  DEV              VARCHAR2(500),
  SKIP_FLAG        VARCHAR2(500),
  IS_LAST          VARCHAR2(1) DEFAULT 'N',
  IS_SAMPLE        VARCHAR2(1) DEFAULT 'N',
  CREATED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_LOG_ISCM_ICT PRIMARY KEY (LOG_ID)
);

-- 조회 인덱스 (BARCODE 단위 DELETE/조회)
CREATE INDEX IX_LOG_ISCM_ICT_BARCODE ON LOG_ISCM_ICT (BARCODE);

-- 컬럼 주석
COMMENT ON COLUMN LOG_ISCM_ICT.BARCODE        IS '제품 바코드';
COMMENT ON COLUMN LOG_ISCM_ICT.TOTAL_RESULT   IS '헤더블록 [RESULT] 보드 전체 판정';
COMMENT ON COLUMN LOG_ISCM_ICT.RESULT_CURRENT IS '헤더블록 [RESULT CURRENT]';
COMMENT ON COLUMN LOG_ISCM_ICT.SEQ_NO         IS 'Component 행 순번(1부터)';
COMMENT ON COLUMN LOG_ISCM_ICT.RESULT         IS 'Component 부품별 판정';

-- ── 3) 작업일자 컬럼 추가 (LOG_ICT 정의 복사, 트리거 전용) ──
DECLARE
  TYPE t_names IS TABLE OF VARCHAR2(128);
  v_cols t_names := t_names('ACTUAL_DATE', 'SHIFT_CODE', 'ZONE_CODE');
  v_type   VARCHAR2(200);
  v_exists NUMBER;
BEGIN
  FOR j IN 1 .. v_cols.COUNT LOOP
    SELECT COUNT(*) INTO v_exists
      FROM user_tab_columns
     WHERE table_name = 'LOG_ISCM_ICT' AND column_name = v_cols(j);
    IF v_exists > 0 THEN CONTINUE; END IF;

    SELECT CASE data_type
             WHEN 'VARCHAR2' THEN 'VARCHAR2(' || data_length || ')'
             WHEN 'CHAR'     THEN 'CHAR(' || data_length || ')'
             WHEN 'NUMBER'   THEN
               CASE WHEN data_precision IS NULL THEN 'NUMBER'
                    ELSE 'NUMBER(' || data_precision || ',' || NVL(data_scale, 0) || ')'
               END
             ELSE data_type
           END
      INTO v_type
      FROM user_tab_columns
     WHERE table_name = 'LOG_ICT' AND column_name = v_cols(j);

    EXECUTE IMMEDIATE 'ALTER TABLE LOG_ISCM_ICT ADD (' || v_cols(j) || ' ' || v_type || ')';
    DBMS_OUTPUT.PUT_LINE('ADDED: LOG_ISCM_ICT.' || v_cols(j) || ' ' || v_type);
  END LOOP;
END;
/

COMMENT ON COLUMN LOG_ISCM_ICT.ACTUAL_DATE IS '작업일자 (트리거 자동 설정)';
COMMENT ON COLUMN LOG_ISCM_ICT.SHIFT_CODE  IS '근무조 (트리거 자동 설정)';
COMMENT ON COLUMN LOG_ISCM_ICT.ZONE_CODE   IS '타임존 (트리거 자동 설정)';
