CREATE OR REPLACE TRIGGER TRG_LOG_COATINGVISION_IS_LAST
BEFORE INSERT ON LOG_COATINGVISION
FOR EACH ROW
BEGIN
  UPDATE LOG_COATINGVISION
  SET IS_LAST = 'N'
  WHERE MAIN_BARCODE = :NEW.MAIN_BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';
END;
/
