CREATE OR REPLACE TRIGGER TRG_LOG_LOWCURRENT_IS_LAST
BEFORE INSERT ON LOG_LOWCURRENT
FOR EACH ROW
BEGIN
  UPDATE LOG_LOWCURRENT
  SET IS_LAST = 'N'
  WHERE BARCODE = :NEW.BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';
END;
/
