CREATE OR REPLACE TRIGGER TRG_LOG_ICT_IS_LAST
BEFORE INSERT ON LOG_ICT
FOR EACH ROW
BEGIN
  UPDATE LOG_ICT
  SET IS_LAST = 'N'
  WHERE BARCODE = :NEW.BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';
END;
/
