CREATE OR REPLACE TRIGGER TRG_LOG_MAOI_IS_LAST
BEFORE INSERT ON LOG_MAOI
FOR EACH ROW
BEGIN
  UPDATE LOG_MAOI
  SET IS_LAST = 'N'
  WHERE SERIAL_NO = :NEW.SERIAL_NO
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';
END;
/
