CREATE OR REPLACE TRIGGER TRG_LOG_EOL_IS_LAST
BEFORE INSERT ON LOG_EOL
FOR EACH ROW
BEGIN
  UPDATE LOG_EOL
  SET IS_LAST = 'N'
  WHERE BARCODE = :NEW.BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';
END;
/
