CREATE OR REPLACE TRIGGER TRG_LOG_FCT_IS_LAST
BEFORE INSERT ON LOG_FCT
FOR EACH ROW
BEGIN
  UPDATE LOG_FCT
  SET IS_LAST = 'N'
  WHERE BARCODE = :NEW.BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';
END;
/
