CREATE OR REPLACE TRIGGER TRG_LOG_SPI_IS_LAST
BEFORE INSERT ON LOG_SPI
FOR EACH ROW
BEGIN
  UPDATE LOG_SPI
  SET IS_LAST = 'N'
  WHERE MASTER_BARCODE = :NEW.MASTER_BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';
END;
/
