CREATE OR REPLACE TRIGGER TRG_LOG_MARKING_IS_LAST
BEFORE INSERT ON LOG_MARKING
FOR EACH ROW
BEGIN
  UPDATE LOG_MARKING
  SET IS_LAST = 'N'
  WHERE MAIN_BARCODE = :NEW.MAIN_BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';
END;
