CREATE OR REPLACE TRIGGER TRG_LOG_VISION_NATIVE_IS_LAST
BEFORE INSERT ON LOG_VISION_NATIVE
FOR EACH ROW
BEGIN
  UPDATE LOG_VISION_NATIVE
  SET IS_LAST = 'N'
  WHERE BARCODE = :NEW.BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';
END;
/
