CREATE OR REPLACE TRIGGER TRG_LOG_AOI_IS_LAST
BEFORE INSERT ON LOG_AOI
FOR EACH ROW
BEGIN
  UPDATE LOG_AOI
  SET IS_LAST = 'N'
  WHERE SERIAL_NO = :NEW.SERIAL_NO
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';
END;
/
