CREATE OR REPLACE TRIGGER TRG_LOG_COATING2_IS_LAST
BEFORE INSERT ON LOG_COATING2
FOR EACH ROW
BEGIN
  UPDATE LOG_COATING2
  SET IS_LAST = 'N'
  WHERE BARCODE = :NEW.BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';
END;
/
