CREATE OR REPLACE TRIGGER TRG_LOG_COATINGREVIEW_IS_LAST
BEFORE INSERT ON LOG_COATINGREVIEW
FOR EACH ROW
BEGIN
  UPDATE LOG_COATINGREVIEW
  SET IS_LAST = 'N'
  WHERE MAIN_BARCODE = :NEW.MAIN_BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';
END;
/
