CREATE OR REPLACE TRIGGER TRG_LOG_COATING1_IS_LAST
BEFORE INSERT ON LOG_COATING1
FOR EACH ROW
BEGIN
  UPDATE LOG_COATING1
  SET IS_LAST = 'N'
  WHERE BARCODE = :NEW.BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';
END;
/
