/**
 * @file src/database/oracle-ddl.ts
 * @description Oracle DDL 자동 생성 빌더 — 테이블/프로시져 DDL + 타입 추론 + 에러 파서
 *
 * 초보자 가이드:
 * 1. **fieldToColumnName**: VRL 파싱 필드명(data.INSPECTOR)을 Oracle 컬럼명(INSPECTOR)으로 변환
 * 2. **inferOracleType**: 필드명 패턴으로 Oracle 데이터 타입 자동 추론
 * 3. **buildCreateTableDDL**: 테이블 CREATE DDL 문 생성
 * 4. **buildCreateProcedureDDL**: INSERT 프로시져 CREATE DDL 문 생성
 * 5. **buildRegistryColumns / buildRegistryProcedure**: 자동 매핑용 registry 데이터 생성
 * 6. **parseOracleError**: ORA 에러 코드를 사용자 메시지로 변환
 */

import type { RegistryColumn, ProcedureEntry, ProcedureParam } from '../config/local-registry.js';

/** 필드 정의 (API 요청에서 전달) */
export interface FieldDef {
  fieldName: string;
  fieldLabel: string;
}

/** 타입 추론 결과 */
export interface OracleTypeDef {
  dataType: string;
  nullable: boolean;
}

/** DDL 생성 결과 */
export interface CreateTableResult {
  ddl: string;
  commentsDDL: string[];
  columns: Array<{ columnName: string; dataType: string; nullable: boolean; isSystem: boolean; sourceField: string; comment: string }>;
}

/** 프로시져 DDL 생성 결과 */
export interface CreateProcedureResult {
  ddl: string;
  params: Array<{ paramName: string; dataType: string; sourceField: string }>;
}

/** 시스템 공통 컬럼 (항상 자동 포함) */
const SYSTEM_COLUMNS = [
  { columnName: 'LOG_ID', dataType: 'NUMBER GENERATED BY DEFAULT AS IDENTITY', nullable: false, sourceField: '', comment: '자동 채번 PK' },
  { columnName: 'EQUIPMENT_ID', dataType: 'VARCHAR2(50)', nullable: false, sourceField: 'equipment_id', comment: '설비 ID' },
  { columnName: 'LOG_TIMESTAMP', dataType: 'TIMESTAMP DEFAULT SYSTIMESTAMP', nullable: true, sourceField: 'timestamp', comment: '로그 타임스탬프' },
];

const SYSTEM_TAIL_COLUMNS = [
  { columnName: 'IS_LAST', dataType: "VARCHAR2(1) DEFAULT 'N'", nullable: true, sourceField: '', comment: '최종 데이터 여부 (Y/N)' },
  { columnName: 'IS_SAMPLE', dataType: "VARCHAR2(1) DEFAULT 'N'", nullable: true, sourceField: '', comment: '샘플 데이터 여부 (Y/N)' },
  { columnName: 'CREATED_AT', dataType: 'TIMESTAMP DEFAULT SYSTIMESTAMP', nullable: true, sourceField: '', comment: '레코드 생성 시각' },
];

/** Oracle 예약어 — 컬럼명으로 사용 시 접두사 추가 필요 */
const ORACLE_RESERVED = new Set([
  'DATE', 'DATETIME', 'TIME', 'TIMESTAMP', 'NUMBER', 'TABLE', 'INDEX', 'ORDER', 'GROUP',
  'SELECT', 'INSERT', 'UPDATE', 'DELETE', 'FROM', 'WHERE', 'AND', 'OR', 'NOT',
  'NULL', 'DEFAULT', 'CHECK', 'CREATE', 'ALTER', 'DROP', 'GRANT', 'REVOKE',
  'SET', 'VALUES', 'INTO', 'AS', 'IS', 'IN', 'ON', 'BY', 'TO', 'OF', 'FOR',
  'WITH', 'LIKE', 'BETWEEN', 'CASE', 'WHEN', 'THEN', 'ELSE', 'END', 'TYPE',
  'LEVEL', 'START', 'CONNECT', 'PRIOR', 'SIZE', 'MODE', 'COMMENT', 'COLUMN',
  'ROW', 'ROWS', 'PRIMARY', 'UNIQUE', 'CONSTRAINT',
]);

/** 한글 필드명 → 영문 컬럼명 매핑 (제조/검사 도메인 공통 용어) */
const KOREAN_TO_ENGLISH: Record<string, string> = {
  '검사결과': 'INSPECT_RESULT', '검사일': 'INSPECT_DATE', '검사일시': 'INSPECT_DATETIME',
  '검사시간': 'INSPECT_TIME', '검사자': 'INSPECTOR', '검사코드': 'INSPECT_CODE',
  '바코드': 'BARCODE', '시리얼번호': 'SERIAL_NO', '시리얼': 'SERIAL_NO',
  '모델명': 'MODEL_NAME', '모델': 'MODEL', '제품명': 'PRODUCT_NAME', '제품코드': 'PRODUCT_CODE',
  '작업자': 'OPERATOR', '작업일': 'WORK_DATE', '작업일시': 'WORK_DATETIME', '작업시간': 'WORK_TIME',
  '불량코드': 'DEFECT_CODE', '불량유형': 'DEFECT_TYPE', '불량수량': 'DEFECT_QTY',
  '설비명': 'EQUIP_NAME', '설비코드': 'EQUIP_CODE', '설비번호': 'EQUIP_NO',
  '라인코드': 'LINE_CODE', '라인': 'LINE_CODE', '라인명': 'LINE_NAME',
  '수량': 'QTY', '양품수량': 'PASS_QTY', '양품': 'PASS_QTY',
  '판정결과': 'JUDGE_RESULT', '판정': 'JUDGMENT', '결과': 'RESULT',
  '날짜': 'LOG_DATE', '시간': 'LOG_TIME', '일시': 'LOG_DATETIME',
  '생성일': 'CREATED_DATE', '수정일': 'MODIFIED_DATE',
  '파일명': 'FILE_NAME', '비고': 'REMARK', '메모': 'MEMO',
  '구분': 'CATEGORY', '유형': 'TYPE_CODE', '상태': 'STATUS',
  '공정': 'PROCESS', '공정명': 'PROCESS_NAME', '공정코드': 'PROCESS_CODE',
  '로트': 'LOT_ID', '로트번호': 'LOT_NO', '기판': 'PCB_ID',
  '온도': 'TEMPERATURE', '습도': 'HUMIDITY', '전압': 'VOLTAGE', '전류': 'CURRENT',
  '양불판정': 'PASS_FAIL', '합격': 'PASS', '불합격': 'FAIL',
};

/** 한글(Hangul) 포함 여부 감지 */
const hasKorean = (s: string) => /[\uAC00-\uD7AF\u3130-\u318F]/.test(s);

/**
 * VRL 파싱 필드명에서 Oracle 컬럼명 추출
 * - 한글 필드명은 영문으로 자동 변환 (미등록 한글은 FIELD_{index} 폴백)
 * - Oracle 예약어는 LOG_ 접두사 자동 추가
 * @example fieldToColumnName('data.INSPECTOR') → 'INSPECTOR'
 * @example fieldToColumnName('data.DATE') → 'LOG_DATE'
 * @example fieldToColumnName('data.검사결과') → 'INSPECT_RESULT'
 * @example fieldToColumnName('data.미등록한글', 3) → 'FIELD_4'
 */
export function fieldToColumnName(fieldName: string, index?: number): string {
  const parts = fieldName.split('.');
  let colName = parts[parts.length - 1];

  if (hasKorean(colName)) {
    const mapped = KOREAN_TO_ENGLISH[colName];
    if (mapped) {
      colName = mapped;
    } else {
      colName = `FIELD_${index !== undefined ? index + 1 : 1}`;
    }
  }

  colName = colName.toUpperCase();
  if (ORACLE_RESERVED.has(colName)) {
    return `LOG_${colName}`;
  }
  return colName;
}

/**
 * 필드명 패턴으로 Oracle 데이터 타입 추론
 * VRL은 모든 필드를 문자열로 파싱하므로 NUMBER 타입은 사용하지 않음.
 * DB 레벨 타입 변환이 필요하면 프로시져에서 TO_NUMBER() 사용.
 * @example inferOracleType('INSPECTIONS') → { dataType: 'CLOB', nullable: true }
 */
export function inferOracleType(fieldName: string): OracleTypeDef {
  const upper = fieldName.toUpperCase();

  if (upper === 'INSPECTIONS' || upper.endsWith('_JSON') || upper.endsWith('_DATA')) {
    return { dataType: 'CLOB', nullable: true };
  }
  if (upper.endsWith('_DATE') || upper.endsWith('_TIME')) {
    return { dataType: 'VARCHAR2(100)', nullable: true };
  }
  if (upper.endsWith('_ID') || upper.endsWith('_CODE')) {
    return { dataType: 'VARCHAR2(100)', nullable: true };
  }
  if (upper.endsWith('_RESULT')) {
    return { dataType: 'VARCHAR2(50)', nullable: true };
  }
  return { dataType: 'VARCHAR2(500)', nullable: true };
}

/**
 * CREATE TABLE DDL 생성
 * @param tableName Oracle 테이블명 (예: LOG_AOI)
 * @param fields VRL 파싱 필드 목록
 */
export function buildCreateTableDDL(tableName: string, fields: FieldDef[]): CreateTableResult {
  const upperName = tableName.toUpperCase();
  const dataColumns = fields.map((f, i) => {
    const colName = fieldToColumnName(f.fieldName, i);
    const typeDef = inferOracleType(colName);
    const comment = f.fieldLabel || f.fieldName;
    return { columnName: colName, dataType: typeDef.dataType, nullable: typeDef.nullable, isSystem: false, sourceField: f.fieldName, comment };
  });

  const allColumns = [
    ...SYSTEM_COLUMNS.map(c => ({ ...c, isSystem: true })),
    ...dataColumns,
    ...SYSTEM_TAIL_COLUMNS.map(c => ({ ...c, isSystem: true })),
  ];

  const colLines = allColumns.map(c => {
    const nullStr = c.nullable ? '' : ' NOT NULL';
    return `  ${c.columnName} ${c.dataType}${nullStr}`;
  });
  colLines.push(`  CONSTRAINT PK_${upperName} PRIMARY KEY (LOG_ID)`);

  const ddl = `CREATE TABLE ${upperName} (\n${colLines.join(',\n')}\n)`;

  /* COMMENT ON COLUMN 문 생성 */
  const commentsDDL = allColumns
    .filter(c => c.comment)
    .map(c => `COMMENT ON COLUMN ${upperName}.${c.columnName} IS '${c.comment.replace(/'/g, "''")}'`);

  return { ddl, commentsDDL, columns: allColumns };
}

/**
 * CREATE OR REPLACE PROCEDURE DDL 생성 (INSERT 프로시져)
 * @param procName 프로시져명 (예: SP_INSERT_AOI)
 * @param tableName INSERT 대상 테이블명
 * @param fields VRL 파싱 필드 목록
 */
export function buildCreateProcedureDDL(procName: string, tableName: string, fields: FieldDef[]): CreateProcedureResult {
  const upperProc = procName.toUpperCase();
  const upperTable = tableName.toUpperCase();
  const now = new Date().toISOString().slice(0, 10);

  const paramDefs = [
    { paramName: 'P_EQUIPMENT_ID', dataType: 'VARCHAR2', sourceField: 'equipment_id', label: '설비 ID' },
    { paramName: 'P_LOG_TIMESTAMP', dataType: 'TIMESTAMP', sourceField: 'timestamp', label: '로그 타임스탬프' },
    ...fields.map((f, i) => {
      const colName = fieldToColumnName(f.fieldName, i);
      const typeDef = inferOracleType(colName);
      const baseType = typeDef.dataType.replace(/\(\d+\)/, '');
      return { paramName: `P_${colName}`, dataType: baseType, sourceField: f.fieldName, label: f.fieldLabel || f.fieldName };
    }),
  ];

  // 파라미터 정렬 시 정렬 폭 계산 (이름 + 타입 패딩)
  const maxNameLen = Math.max(...paramDefs.map(p => p.paramName.length));
  const maxTypeLen = Math.max(...paramDefs.map(p => `IN ${p.dataType}`.length));

  const paramLines = paramDefs.map((p, i) => {
    const comma = i < paramDefs.length - 1 ? ',' : ' ';
    const namepad = p.paramName.padEnd(maxNameLen);
    const typeStr = `IN ${p.dataType}`.padEnd(maxTypeLen);
    return `  ${namepad}  ${typeStr}${comma} -- ${p.label}`;
  });

  const insertItems = [
    { col: 'EQUIPMENT_ID', val: 'P_EQUIPMENT_ID', label: '설비 ID' },
    { col: 'LOG_TIMESTAMP', val: 'P_LOG_TIMESTAMP', label: '로그 타임스탬프' },
    ...fields.map((f, i) => {
      const colName = fieldToColumnName(f.fieldName, i);
      return { col: colName, val: `P_${colName}`, label: f.fieldLabel || f.fieldName };
    }),
  ];

  const maxColLen = Math.max(...insertItems.map(x => x.col.length));
  const maxValLen = Math.max(...insertItems.map(x => x.val.length));

  // INSERT 컬럼/VALUES를 줄바꿈 포맷팅 + 설명 주석
  const colLines = insertItems.map((x, i) => {
    const comma = i < insertItems.length - 1 ? ',' : ' ';
    return `      ${x.col.padEnd(maxColLen)}${comma} -- ${x.label}`;
  });
  const valLines = insertItems.map((x, i) => {
    const comma = i < insertItems.length - 1 ? ',' : ' ';
    return `      ${x.val.padEnd(maxValLen)}${comma} -- ${x.label}`;
  });

  const ddl = [
    `-- ==========================================================`,
    `-- ${upperProc}`,
    `-- 설명: ${upperTable} 테이블 INSERT 프로시져 (자동 생성)`,
    `-- 대상: ${upperTable}`,
    `-- 생성: ${now} (Vector 매핑 자동생성)`,
    `-- 파라미터: ${paramDefs.length}개`,
    `-- ==========================================================`,
    `CREATE OR REPLACE PROCEDURE ${upperProc} (`,
    paramLines.join('\n'),
    `) AS`,
    `BEGIN`,
    `  INSERT INTO ${upperTable} (`,
    colLines.join('\n'),
    `  ) VALUES (`,
    valLines.join('\n'),
    `  );`,
    `  COMMIT;`,
    `EXCEPTION`,
    `  WHEN OTHERS THEN`,
    `    ROLLBACK;`,
    `    RAISE;`,
    `END ${upperProc};`,
  ].join('\n');

  return { ddl, params: paramDefs };
}

/**
 * 자동 매핑용 registry 컬럼 배열 생성 (TABLE 타겟)
 * @param tableName 테이블명
 * @param fields VRL 파싱 필드 목록
 */
export function buildRegistryColumns(tableName: string, fields: FieldDef[]): RegistryColumn[] {
  const columns: RegistryColumn[] = [];
  let order = 1;

  columns.push({
    COLUMN_NAME: 'EQUIPMENT_ID', DATA_TYPE: 'VARCHAR2(50)',
    SOURCE_FIELD: 'equipment_id', IS_REQUIRED: 'Y', COLUMN_ORDER: order++,
  });
  columns.push({
    COLUMN_NAME: 'LOG_TIMESTAMP', DATA_TYPE: 'TIMESTAMP',
    SOURCE_FIELD: 'timestamp', IS_REQUIRED: 'N', COLUMN_ORDER: order++,
  });

  fields.forEach((f, i) => {
    const colName = fieldToColumnName(f.fieldName, i);
    const typeDef = inferOracleType(colName);
    columns.push({
      COLUMN_NAME: colName, DATA_TYPE: typeDef.dataType,
      SOURCE_FIELD: f.fieldName, IS_REQUIRED: 'N', COLUMN_ORDER: order++,
    });
  });

  return columns;
}

/**
 * 자동 매핑용 procedure entry 생성 (PROCEDURE 타겟)
 * @param procName 프로시져명
 * @param fields VRL 파싱 필드 목록
 */
export function buildRegistryProcedure(procName: string, fields: FieldDef[]): ProcedureEntry {
  const params: ProcedureParam[] = [];
  let order = 1;

  params.push({
    PARAM_ORDER: order++, ARGUMENT_NAME: 'P_EQUIPMENT_ID',
    DATA_TYPE: 'VARCHAR2', IN_OUT: 'IN', SOURCE_FIELD: 'equipment_id', IS_REQUIRED: 'Y',
  });
  params.push({
    PARAM_ORDER: order++, ARGUMENT_NAME: 'P_LOG_TIMESTAMP',
    DATA_TYPE: 'TIMESTAMP', IN_OUT: 'IN', SOURCE_FIELD: 'timestamp', IS_REQUIRED: 'N',
  });

  fields.forEach((f, i) => {
    const colName = fieldToColumnName(f.fieldName, i);
    const typeDef = inferOracleType(colName);
    const baseType = typeDef.dataType.replace(/\(\d+\)/, '');
    params.push({
      PARAM_ORDER: order++, ARGUMENT_NAME: `P_${colName}`,
      DATA_TYPE: baseType, IN_OUT: 'IN', SOURCE_FIELD: f.fieldName, IS_REQUIRED: 'N',
    });
  });

  return {
    targetType: 'PROCEDURE',
    procedureName: procName.toUpperCase(),
    callMode: 'NAMED',
    params,
  };
}

/** ORA 에러 코드별 사용자 메시지 반환 */
export function parseOracleError(err: unknown): { code: string; message: string } {
  const msg = err instanceof Error ? err.message : String(err);

  if (msg.includes('ORA-00955')) {
    return { code: 'ORA-00955', message: 'alreadyExists' };
  }
  if (msg.includes('ORA-01031')) {
    return { code: 'ORA-01031', message: 'noPrivilege' };
  }
  if (msg.includes('ORA-00972')) {
    return { code: 'ORA-00972', message: 'nameTooLong' };
  }
  return { code: 'UNKNOWN', message: msg };
}
