/**
 * @file src/database/oracle-ddl.ts
 * @description Oracle DDL 자동 생성 빌더 — 테이블/프로시져 DDL + 타입 추론 + 에러 파서
 *
 * 초보자 가이드:
 * 1. **fieldToColumnName**: VRL 파싱 필드명(data.INSPECTOR)을 Oracle 컬럼명(INSPECTOR)으로 변환
 * 2. **inferOracleType**: 필드명 패턴으로 Oracle 데이터 타입 자동 추론
 * 3. **buildCreateTableDDL**: 테이블 CREATE DDL 문 생성
 * 4. **buildCreateProcedureDDL**: INSERT 프로시져 CREATE DDL 문 생성
 * 5. **buildRegistryColumns / buildRegistryProcedure**: 자동 매핑용 registry 데이터 생성
 * 6. **parseOracleError**: ORA 에러 코드를 사용자 메시지로 변환
 */

import type { RegistryColumn, ProcedureEntry, ProcedureParam } from '../config/local-registry.js';

/** 필드 정의 (API 요청에서 전달) */
export interface FieldDef {
  fieldName: string;
  fieldLabel: string;
}

/** 타입 추론 결과 */
export interface OracleTypeDef {
  dataType: string;
  nullable: boolean;
}

/** DDL 생성 결과 */
export interface CreateTableResult {
  ddl: string;
  columns: Array<{ columnName: string; dataType: string; nullable: boolean; isSystem: boolean; sourceField: string }>;
}

/** 프로시져 DDL 생성 결과 */
export interface CreateProcedureResult {
  ddl: string;
  params: Array<{ paramName: string; dataType: string; sourceField: string }>;
}

/** 시스템 공통 컬럼 (항상 자동 포함) */
const SYSTEM_COLUMNS = [
  { columnName: 'LOG_ID', dataType: 'NUMBER GENERATED BY DEFAULT AS IDENTITY', nullable: false, sourceField: '' },
  { columnName: 'EQUIPMENT_ID', dataType: 'VARCHAR2(50)', nullable: false, sourceField: 'equipment_id' },
  { columnName: 'LOG_TIMESTAMP', dataType: 'TIMESTAMP DEFAULT SYSTIMESTAMP', nullable: true, sourceField: 'timestamp' },
];

const SYSTEM_TAIL_COLUMNS = [
  { columnName: 'CREATED_AT', dataType: 'TIMESTAMP DEFAULT SYSTIMESTAMP', nullable: true, sourceField: '' },
];

/**
 * VRL 파싱 필드명에서 Oracle 컬럼명 추출
 * @example fieldToColumnName('data.INSPECTOR') → 'INSPECTOR'
 */
export function fieldToColumnName(fieldName: string): string {
  const parts = fieldName.split('.');
  return parts[parts.length - 1].toUpperCase();
}

/**
 * 필드명 패턴으로 Oracle 데이터 타입 추론
 * @example inferOracleType('INSPECTIONS') → { dataType: 'CLOB', nullable: true }
 */
export function inferOracleType(fieldName: string): OracleTypeDef {
  const upper = fieldName.toUpperCase();

  if (upper === 'INSPECTIONS' || upper.endsWith('_JSON') || upper.endsWith('_DATA')) {
    return { dataType: 'CLOB', nullable: true };
  }
  if (upper.endsWith('_COUNT') || upper.endsWith('_QTY') || upper.endsWith('_NUM')) {
    return { dataType: 'NUMBER', nullable: true };
  }
  if (upper.endsWith('_DATE') || upper.endsWith('_TIME')) {
    return { dataType: 'VARCHAR2(100)', nullable: true };
  }
  if (upper.endsWith('_ID') || upper.endsWith('_CODE')) {
    return { dataType: 'VARCHAR2(100)', nullable: true };
  }
  if (upper.endsWith('_RESULT')) {
    return { dataType: 'VARCHAR2(50)', nullable: true };
  }
  return { dataType: 'VARCHAR2(500)', nullable: true };
}

/**
 * CREATE TABLE DDL 생성
 * @param tableName Oracle 테이블명 (예: LOG_AOI)
 * @param fields VRL 파싱 필드 목록
 */
export function buildCreateTableDDL(tableName: string, fields: FieldDef[]): CreateTableResult {
  const upperName = tableName.toUpperCase();
  const dataColumns = fields.map(f => {
    const colName = fieldToColumnName(f.fieldName);
    const typeDef = inferOracleType(colName);
    return { columnName: colName, dataType: typeDef.dataType, nullable: typeDef.nullable, isSystem: false, sourceField: f.fieldName };
  });

  const allColumns = [
    ...SYSTEM_COLUMNS.map(c => ({ ...c, isSystem: true })),
    ...dataColumns,
    ...SYSTEM_TAIL_COLUMNS.map(c => ({ ...c, isSystem: true })),
  ];

  const colLines = allColumns.map(c => {
    const nullStr = c.nullable ? '' : ' NOT NULL';
    return `  ${c.columnName} ${c.dataType}${nullStr}`;
  });
  colLines.push(`  CONSTRAINT PK_${upperName} PRIMARY KEY (LOG_ID)`);

  const ddl = `CREATE TABLE ${upperName} (\n${colLines.join(',\n')}\n)`;

  return { ddl, columns: allColumns };
}

/**
 * CREATE OR REPLACE PROCEDURE DDL 생성 (INSERT 프로시져)
 * @param procName 프로시져명 (예: SP_INSERT_AOI)
 * @param tableName INSERT 대상 테이블명
 * @param fields VRL 파싱 필드 목록
 */
export function buildCreateProcedureDDL(procName: string, tableName: string, fields: FieldDef[]): CreateProcedureResult {
  const upperProc = procName.toUpperCase();
  const upperTable = tableName.toUpperCase();

  const paramDefs = [
    { paramName: 'P_EQUIPMENT_ID', dataType: 'VARCHAR2', sourceField: 'equipment_id' },
    ...fields.map(f => {
      const colName = fieldToColumnName(f.fieldName);
      const typeDef = inferOracleType(colName);
      const baseType = typeDef.dataType.replace(/\(\d+\)/, '');
      return { paramName: `P_${colName}`, dataType: baseType, sourceField: f.fieldName };
    }),
  ];

  const paramLines = paramDefs.map((p, i) => {
    const comma = i < paramDefs.length - 1 ? ',' : '';
    return `  ${p.paramName} IN ${p.dataType}${comma}`;
  });

  const insertCols = ['EQUIPMENT_ID', ...fields.map(f => fieldToColumnName(f.fieldName))];
  const insertVals = ['P_EQUIPMENT_ID', ...fields.map(f => `P_${fieldToColumnName(f.fieldName)}`)];

  const ddl = [
    `CREATE OR REPLACE PROCEDURE ${upperProc} (`,
    paramLines.join('\n'),
    `) AS`,
    `BEGIN`,
    `  INSERT INTO ${upperTable} (${insertCols.join(', ')})`,
    `  VALUES (${insertVals.join(', ')});`,
    `  COMMIT;`,
    `END ${upperProc};`,
  ].join('\n');

  return { ddl, params: paramDefs };
}

/**
 * 자동 매핑용 registry 컬럼 배열 생성 (TABLE 타겟)
 * @param tableName 테이블명
 * @param fields VRL 파싱 필드 목록
 */
export function buildRegistryColumns(tableName: string, fields: FieldDef[]): RegistryColumn[] {
  const columns: RegistryColumn[] = [];
  let order = 1;

  columns.push({
    COLUMN_NAME: 'EQUIPMENT_ID', DATA_TYPE: 'VARCHAR2(50)',
    SOURCE_FIELD: 'equipment_id', IS_REQUIRED: 'Y', COLUMN_ORDER: order++,
  });
  columns.push({
    COLUMN_NAME: 'LOG_TIMESTAMP', DATA_TYPE: 'TIMESTAMP',
    SOURCE_FIELD: 'timestamp', IS_REQUIRED: 'N', COLUMN_ORDER: order++,
  });

  for (const f of fields) {
    const colName = fieldToColumnName(f.fieldName);
    const typeDef = inferOracleType(colName);
    columns.push({
      COLUMN_NAME: colName, DATA_TYPE: typeDef.dataType,
      SOURCE_FIELD: f.fieldName, IS_REQUIRED: 'N', COLUMN_ORDER: order++,
    });
  }

  return columns;
}

/**
 * 자동 매핑용 procedure entry 생성 (PROCEDURE 타겟)
 * @param procName 프로시져명
 * @param fields VRL 파싱 필드 목록
 */
export function buildRegistryProcedure(procName: string, fields: FieldDef[]): ProcedureEntry {
  const params: ProcedureParam[] = [];
  let order = 1;

  params.push({
    PARAM_ORDER: order++, ARGUMENT_NAME: 'P_EQUIPMENT_ID',
    DATA_TYPE: 'VARCHAR2', IN_OUT: 'IN', SOURCE_FIELD: 'equipment_id', IS_REQUIRED: 'Y',
  });

  for (const f of fields) {
    const colName = fieldToColumnName(f.fieldName);
    const typeDef = inferOracleType(colName);
    const baseType = typeDef.dataType.replace(/\(\d+\)/, '');
    params.push({
      PARAM_ORDER: order++, ARGUMENT_NAME: `P_${colName}`,
      DATA_TYPE: baseType, IN_OUT: 'IN', SOURCE_FIELD: f.fieldName, IS_REQUIRED: 'N',
    });
  }

  return {
    targetType: 'PROCEDURE',
    procedureName: procName.toUpperCase(),
    callMode: 'NAMED',
    params,
  };
}

/** ORA 에러 코드별 사용자 메시지 반환 */
export function parseOracleError(err: unknown): { code: string; message: string } {
  const msg = err instanceof Error ? err.message : String(err);

  if (msg.includes('ORA-00955')) {
    return { code: 'ORA-00955', message: 'alreadyExists' };
  }
  if (msg.includes('ORA-01031')) {
    return { code: 'ORA-01031', message: 'noPrivilege' };
  }
  if (msg.includes('ORA-00972')) {
    return { code: 'ORA-00972', message: 'nameTooLong' };
  }
  return { code: 'UNKNOWN', message: msg };
}
