-- =============================================================================
-- 04_create_indexes.sql
-- 성능 최적화를 위한 인덱스 생성
-- 주요 조회 패턴: equipment_id별, 시간대별, 알람코드/레벨별 검색
-- =============================================================================

-- LOG_INSPECTION indexes
CREATE INDEX IDX_INSP_EQUIP_ID  ON LOG_INSPECTION(EQUIPMENT_ID);
CREATE INDEX IDX_INSP_TIMESTAMP ON LOG_INSPECTION(LOG_TIMESTAMP);
CREATE INDEX IDX_INSP_CREATED   ON LOG_INSPECTION(CREATED_AT);

-- LOG_ALARM indexes
CREATE INDEX IDX_ALARM_EQUIP_ID  ON LOG_ALARM(EQUIPMENT_ID);
CREATE INDEX IDX_ALARM_TIMESTAMP ON LOG_ALARM(LOG_TIMESTAMP);
CREATE INDEX IDX_ALARM_CODE      ON LOG_ALARM(ALARM_CODE);
CREATE INDEX IDX_ALARM_LEVEL     ON LOG_ALARM(ALARM_LEVEL);

-- LOG_PROCESS indexes
CREATE INDEX IDX_PROC_EQUIP_ID  ON LOG_PROCESS(EQUIPMENT_ID);
CREATE INDEX IDX_PROC_TIMESTAMP ON LOG_PROCESS(LOG_TIMESTAMP);
CREATE INDEX IDX_PROC_STEP      ON LOG_PROCESS(PROCESS_STEP);

-- LOG_ERROR indexes
CREATE INDEX IDX_ERR_SOURCE   ON LOG_ERROR(SOURCE_TABLE);
CREATE INDEX IDX_ERR_EQUIP_ID ON LOG_ERROR(EQUIPMENT_ID);
CREATE INDEX IDX_ERR_CREATED  ON LOG_ERROR(CREATED_AT);

-- TABLE_COLUMN_REGISTRY indexes
CREATE INDEX IDX_REG_TABLE ON TABLE_COLUMN_REGISTRY(TABLE_NAME);
