CREATE OR REPLACE TRIGGER TRG_LOG_EOL_IS_LAST
BEFORE INSERT ON LOG_EOL
FOR EACH ROW
BEGIN
  UPDATE LOG_EOL
  SET IS_LAST = 'N'
  WHERE BARCODE = :NEW.BARCODE
    AND IS_LAST = 'Y';
  :NEW.IS_LAST := 'Y';

  IF :NEW.ARRAY_RESULT IS NOT NULL
     AND UPPER(:NEW.ARRAY_RESULT) NOT IN ('PASS','OK','GOOD','Y') THEN
    P_AUTO_INSERT_QC(:NEW.BARCODE, :NEW.LOG_ID, :NEW.EQUIPMENT_ID, 'W155', :NEW.FILE_NAME);
  END IF;
END;
